"""
Byte-level autoregressive text generation for HatchlingLM.

Supports temperature sweeps, top-k filtering, and automatic UTF-8 byte
stream decoding without any tokenizer dependency.
"""

from typing import Optional
import torch
import torch.nn.functional as F


@torch.no_grad()
def generate(
    model: torch.nn.Module,
    prompt: str = "ROMEO:\n",
    max_new_tokens: int = 300,
    temperature: float = 0.8,
    top_k: Optional[int] = 40,
    device: str = "cuda"
) -> str:
    """
    Generates text autoregressively conditioned on a UTF-8 text prompt.

    Args:
        model: HatchlingLM or autoregressive language model.
        prompt: Initial conditioning string.
        max_new_tokens: Number of bytes to generate.
        temperature: Softmax temperature (>0.0, lower is more conservative).
        top_k: Top-k filtering threshold (None disables top-k).
        device: Device to run generation on ("cuda" or "cpu").

    Returns:
        Decoded text string from the generated byte stream.
    """
    model.eval()

    # Encode prompt directly to UTF-8 byte tensor
    prompt_bytes = list(prompt.encode("utf-8"))
    idx = torch.tensor([prompt_bytes], dtype=torch.long, device=device)

    max_seq_len = getattr(model, "max_seq_len", 128)

    for _ in range(max_new_tokens):
        # Crop context to model's maximum sequence length
        idx_cond = idx[:, -max_seq_len:] if idx.size(1) > max_seq_len else idx

        # Forward pass
        logits, _ = model(idx_cond)

        # Extract logits at the final timestep and scale by temperature
        logits = logits[:, -1, :] / max(temperature, 1e-5)

        # Optional Top-K filtering
        if top_k is not None:
            v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
            logits[logits < v[:, [-1]]] = -float("Inf")

        # Softmax to probability distribution
        probs = F.softmax(logits, dim=-1)

        # Sample next byte
        next_byte = torch.multinomial(probs, num_samples=1)

        # Append to running sequence
        idx = torch.cat((idx, next_byte), dim=1)

    generated_bytes = bytes(idx[0].tolist())
    return generated_bytes.decode("utf-8", errors="replace")
